-- V31: Seed 430 additional ATS boards, verified against their live public APIs.
--
-- Every token here was probed on 2026-09-21 against the endpoint the connector
-- actually calls, and kept only if the board answered AND carried at least ten
-- postings that pass the same United States location test the sync applies
-- (CandidateJobSearchService.hasUnitedStatesSignal). Tokens that 404'd, returned
-- an empty board, or were entirely non-US were discarded rather than seeded --
-- V17 seeded 270 guessed tokens and 126 of its Greenhouse boards were later
-- auto-disabled on 404, which is the failure this verification exists to avoid.
--
-- 9,079 candidate tokens were probed to find these 430. The hit rate is worth
-- recording because it says where the remaining supply is NOT: tokens aimed at
-- venture-backed technology companies landed around one in six, while tokens
-- aimed at regional hospitals, school districts, trucking, grocery and staffing
-- landed around one in fifty. Those employers are real and large, but they are on
-- Workday, iCIMS, Taleo and UKG, not on these three boards. Growing past this set
-- means another connector, not more guessing here.
--
-- Measured US postings behind these boards at seed time:
--   Ashby          64 boards
--   Greenhouse    317 boards
--   Lever          49 boards
--   TOTAL         430 boards, 25,734 US postings listed
--
-- domain and logo_url are left NULL. Guessing <token>.com would give the brand
-- enrichment a wrong favicon to cache, and a missing logo is recoverable where a
-- confidently wrong one is not.

WITH companies(name, normalized_name) AS (
    VALUES
        ('4D Molecular Therapeutics', '4dmoleculartherapeutics'),
        ('6sense', '6sense'),
        ('ABACUS', 'abacus'),
        ('Abnormal', 'abnormalsecurity'),
        ('Absorblms', 'absorblms'),
        ('Accela', 'accela'),
        ('Achievement First (Teaching)', 'achievementfirst'),
        ('ACLU - National Office', 'aclu'),
        ('Adyen', 'adyen'),
        ('AEG Worldwide', 'aegworldwide'),
        ('Aeva', 'aeva'),
        ('AfterShip', 'aftership'),
        ('Agility Robotics', 'agilityrobotics'),
        ('Airwallex', 'airwallex'),
        ('Albedo', 'albedo'),
        ('Aledade', 'aledade'),
        ('AlertMedia', 'alertmedia'),
        ('Allegiantair', 'allegiantair'),
        ('Alloy', 'alloy'),
        ('Alnylam Pharmaceuticals', 'alnylampharmaceuticals'),
        ('ALO', 'aloyoga'),
        ('AlphaSights', 'alphasights'),
        ('Altos Labs', 'altoslabs'),
        ('Altruist', 'altruist'),
        ('ARCO/Murray National Construction', 'amn'),
        ('Amplify', 'amplify'),
        ('Amwins', 'amwins'),
        ('Anaplan', 'anaplan'),
        ('Anchorage', 'anchorage'),
        ('Angellist', 'angellist'),
        ('Angi', 'angi'),
        ('Antora Energy', 'antora'),
        ('Apex Companies', 'apexcompanies'),
        ('Applied', 'applied'),
        ('AppLovin', 'applovin'),
        ('Apptronik', 'apptronik'),
        ('AQR', 'aqr'),
        ('Arcadia', 'arcadia'),
        ('Arc Institute', 'arcinstitute'),
        ('Arrivelogistics', 'arrivelogistics'),
        ('Asana', 'asana'),
        ('Assembledhq', 'assembledhq'),
        ('Asset Living', 'assetliving'),
        ('Astra', 'astra'),
        ('Astranis', 'astranis'),
        ('Atlas Air', 'atlasair'),
        ('Attentive', 'attentive'),
        ('Axios', 'axios'),
        ('Axsome Therapeutics', 'axsometherapeutics'),
        ('Aya Healthcare', 'ayahealthcare'),
        ('Bandwidth', 'bandwidth'),
        ('Bankrate', 'bankrate'),
        ('Bannerbank', 'bannerbank'),
        ('Beam Therapeutics', 'beamtherapeutics'),
        ('Benchling', 'benchling'),
        ('Bestow', 'bestow'),
        ('Betterment', 'betterment'),
        ('BeyondTrust', 'beyondtrust'),
        ('BILL', 'billcom'),
        ('Bird', 'bird'),
        ('BitGo', 'bitgo'),
        ('BlackSky', 'blacksky'),
        ('Blank Street', 'blankstreet'),
        ('Blend', 'blend'),
        ('Bluebottlecoffee', 'bluebottlecoffee'),
        ('Bombas', 'bombas'),
        ('Boulder Care', 'bouldercare'),
        ('Bounteous', 'bounteous'),
        ('Brainlabs', 'brainlabs'),
        ('Braze', 'braze'),
        ('BridgeBio Pharma', 'bridgebio'),
        ('Brightwheel', 'brightwheel'),
        ('Brigit', 'brigit'),
        ('Brooksrunning', 'brooksrunning'),
        ('Budderfly', 'budderfly'),
        ('BuildOps', 'buildops'),
        ('Businessolver', 'businessolver'),
        ('Butterfly Network', 'butterflynetwork'),
        ('Calico', 'calicolabs'),
        ('CannonDesign', 'cannondesign'),
        ('Capco', 'capco'),
        ('Carbon, Inc.', 'carbon'),
        ('Carbon Robotics', 'carbonrobotics'),
        ('24 Hour Home Care - Caregiver Division', 'caregiver'),
        ('CarGurus', 'cargurus'),
        ('Carta', 'carta'),
        ('Celigo', 'celigo'),
        ('Chan Zuckerberg Initiative', 'chanzuckerberginitiative'),
        ('ChargePoint', 'chargepoint'),
        ('Charles River Associates', 'charlesriverassociates'),
        ('Charlie Health', 'charliehealth'),
        ('Checkr', 'checkr'),
        ('ClassPass', 'classpass'),
        ('Clear Street', 'clearstreet'),
        ('Clickhouse', 'clickhouse'),
        ('Clickup', 'clickup'),
        ('Clover Health', 'cloverhealth'),
        ('Coalition, Inc.', 'coalition'),
        ('Code and Theory', 'codeandtheory'),
        ('Collibra', 'collibra'),
        ('Colossal Biosciences', 'colossalbiosciences'),
        ('Commure', 'commure'),
        ('Commvault', 'commvault'),
        ('Conga', 'conga'),
        ('Cortland', 'cortland'),
        ('Cross River', 'crossriverbank'),
        ('Crunchyroll, LLC', 'crunchyroll'),
        ('Curri', 'curri'),
        ('Cypress Creek Renewables', 'cypresscreekrenewables'),
        ('Dadavidson', 'dadavidson'),
        ('Dandelion', 'dandelion'),
        ('DataCamp', 'datacamp'),
        ('Dealpath', 'dealpath'),
        ('Delinea', 'delinea'),
        ('Deposco', 'deposco'),
        ('Dialpad', 'dialpad'),
        ('Diligent Robotics', 'diligentrobotics'),
        ('DISCO', 'disco'),
        ('Divergent', 'divergent'),
        ('DLR Group', 'dlrgroup'),
        ('Docker', 'docker'),
        ('Dotmatics', 'dotmatics'),
        ('Dragos', 'dragos'),
        ('Dyne Therapeutics', 'dynetherapeutics'),
        ('EarnIn', 'earnin'),
        ('Edgewise Therapeutics', 'edgewisetherapeutics'),
        ('Edmentum', 'edmentum'),
        ('Eightsleep', 'eightsleep'),
        ('Elation Health', 'elationhealth'),
        ('Electra', 'electraaero'),
        ('Elevations Credit Union', 'elevationscreditunion'),
        ('Elite Physical Therapy, Inc.', 'elite'),
        ('Entrata', 'entrata'),
        ('Envoy', 'envoy'),
        ('Epirus', 'epirus'),
        ('Everlane', 'everlane'),
        ('Everlaw', 'everlaw'),
        ('Everlywell', 'everlywell'),
        ('Exiger', 'exiger'),
        ('Faherty Brand', 'fahertybrand'),
        ('Fastly', 'fastly'),
        ('Fictiv', 'fictiv'),
        ('Fieldwire', 'fieldwire'),
        ('Filevine', 'filevine'),
        ('Fireblocks', 'fireblocks'),
        ('Five9', 'five9'),
        ('Fleetio', 'fleetio'),
        ('Flix', 'flix'),
        ('Forbes', 'forbes'),
        ('Formenergy', 'formenergy'),
        ('Formic', 'formic'),
        ('Freedomprep', 'freedomprep'),
        ('Freenome', 'freenome'),
        ('Galileo', 'galileo'),
        ('Gemini', 'gemini'),
        ('Generate Biomedicines', 'generatebiomedicines'),
        ('Genius Sports', 'geniussports'),
        ('Geotab', 'geotab'),
        ('GILLIG', 'gillig'),
        ('Ginkgo Bioworks Inc.', 'ginkgobioworks'),
        ('G-P', 'globalizationpartners'),
        ('Glossier', 'glossier'),
        ('Motive', 'gomotive'),
        ('GFiber', 'googlefiber'),
        ('Gopuff', 'gopuff'),
        ('Guidepoint', 'guidepoint'),
        ('Handshake', 'handshake'),
        ('Harbinger Motors Inc.', 'harbingermotors'),
        ('Harry''s', 'harrys'),
        ('Hasbro', 'hasbro'),
        ('HawkEye 360', 'hawkeye360'),
        ('HealthVerity', 'healthverity'),
        ('Hearst', 'hearst'),
        ('Helion', 'helion'),
        ('HelloFresh', 'hellofresh'),
        ('Hermeus', 'hermeus'),
        ('Hex Technologies', 'hextechnologies'),
        ('Holder Construction', 'holderconstruction'),
        ('Home Chef', 'homechef'),
        ('HomeLight', 'homelight'),
        ('HugeInc', 'hugeinc'),
        ('Huntress', 'huntress'),
        ('Hyliion', 'hyliion'),
        ('IMC', 'imc'),
        ('Industrious', 'industrious'),
        ('Inovalon', 'inovalon'),
        ('Insitro', 'insitro'),
        ('Insomniacookies', 'insomniacookies'),
        ('Instructure', 'instructure'),
        ('Fin', 'intercom'),
        ('Iovance Biotherapeutics', 'iovancebiotherapeutics'),
        ('Isomorphic Labs', 'isomorphiclabs'),
        ('IXL Learning', 'ixllearning'),
        ('Jamcity', 'jamcity'),
        ('Jane Street', 'janestreet'),
        ('Jetsupport', 'jetsupport'),
        ('Junipersquare', 'junipersquare'),
        ('Kailera Therapeutics, Inc.', 'kailera'),
        ('Kairos Power', 'kairospower'),
        ('Kelso Building Services', 'kbs'),
        ('Keeper Security', 'keepersecurity'),
        ('Kin', 'kin'),
        ('Kiniksa Pharmaceuticals', 'kiniksapharmaceuticals'),
        ('Kippsocal', 'kippsocal'),
        ('KnowBe4', 'knowbe4'),
        ('Kodiak', 'kodiak'),
        ('Komodo Health', 'komodohealth'),
        ('Kong', 'kong'),
        ('Kymera Therapeutics', 'kymeratherapeutics'),
        ('Langchain', 'langchain'),
        ('Latchbio', 'latchbio'),
        ('LendingTree', 'lendingtree'),
        ('Lessen', 'lessen'),
        ('Lifestance', 'lifestance'),
        ('Liftoff', 'liftoff'),
        ('Lightmatter', 'lightmatter'),
        ('Litify', 'litify'),
        ('LogicGate', 'logicgate'),
        ('Little People''s Landing', 'lpl'),
        ('Lucid Motors', 'lucidmotors'),
        ('Luminis Health', 'luminishealth'),
        ('Lyft', 'lyft'),
        ('Mach Industries', 'machindustries'),
        ('Maven Clinic', 'mavenclinic'),
        ('McAdams', 'mcadams'),
        ('Melio', 'melio'),
        ('Meridianlink', 'meridianlink'),
        ('Merlinlabs', 'merlinlabs'),
        ('Method', 'method'),
        ('Method Communications', 'methodcommunications'),
        ('MinIO', 'minio'),
        ('Misfits Market', 'misfitsmarket'),
        ('Mission Lane', 'missionlane'),
        ('Mixpanel', 'mixpanel'),
        ('MNTN', 'mntn'),
        ('Moloco', 'moloco'),
        ('Monks', 'monks'),
        ('Mozilla', 'mozilla'),
        ('Muon Space', 'muonspace'),
        ('Natera', 'natera'),
        ('Naughty Dog', 'naughtydog'),
        ('Neo4j', 'neo4j'),
        ('Nerdwallet', 'nerdwallet'),
        ('Netskope', 'netskope'),
        ('Neuralink', 'neuralink'),
        ('New Relic', 'newrelic'),
        ('Newsela', 'newsela'),
        ('Nex', 'nex'),
        ('Nexamp', 'nexamp'),
        ('NICE', 'nice'),
        ('Nintendo', 'nintendo'),
        ('Notable', 'notable'),
        ('Nubank', 'nubank'),
        ('Nurix', 'nurix'),
        ('Nuro', 'nuro'),
        ('Office Ally', 'officeally'),
        ('Ogilvy', 'ogilvy'),
        ('Oklo', 'oklo'),
        ('Olema Oncology', 'olema'),
        ('Olsson', 'olsson'),
        ('Omada Health', 'omadahealth'),
        ('One Medical', 'onemedical'),
        ('On', 'onrunning'),
        ('Opengov', 'opengov'),
        ('OpenTable', 'opentable'),
        ('Ophelia', 'ophelia'),
        ('Oportun', 'oportun'),
        ('Orchard', 'orchard'),
        ('Otter', 'otter'),
        ('Ōura', 'oura'),
        ('Pacific Fusion', 'pacificfusion'),
        ('Pagaya', 'pagaya'),
        ('Parachute Home', 'parachutehome'),
        ('Path Robotics', 'pathrobotics'),
        ('Pattern', 'pattern'),
        ('Paxos', 'paxos'),
        ('Picklerobot', 'picklerobot'),
        ('Pie Insurance', 'pieinsurance'),
        ('Pigment', 'pigment'),
        ('Planet', 'planetlabs'),
        ('Point72', 'point72'),
        ('Pointclickcare', 'pointclickcare'),
        ('Poshmark', 'poshmark'),
        ('Primer', 'primer'),
        ('Prosper', 'prosper'),
        ('Protolabs', 'protolabs'),
        ('Prove', 'prove'),
        ('PsiQuantum', 'psiquantum'),
        ('PubMatic', 'pubmatic'),
        ('Everpure', 'purestorage'),
        ('Quality Trusted Commercial', 'qt'),
        ('Quaise Energy, Inc', 'quaise'),
        ('Qualia', 'qualia'),
        ('Re:Build Manufacturing', 'rebuildmanufacturing'),
        ('Recursion', 'recursionpharmaceuticals'),
        ('Redwoodcu', 'redwoodcu'),
        ('Redwood Materials', 'redwoodmaterials'),
        ('Reformation', 'reformation'),
        ('Relativity Space', 'relativity'),
        ('Rent the Runway', 'renttherunway'),
        ('Revolution Medicines', 'revolutionmedicines'),
        ('Riot Games', 'riotgames'),
        ('Roblox', 'roblox'),
        ('Rocket Lab Corporation', 'rocketlab'),
        ('Rocketship', 'rocketship'),
        ('Rockstar Games', 'rockstargames'),
        ('Roku', 'roku'),
        ('Roofstock', 'roofstock'),
        ('Rothys', 'rothys'),
        ('Real-Time Innovations', 'rti'),
        ('Rubrik Job Board', 'rubrik'),
        ('Runpod', 'runpod'),
        ('Saatva', 'saatva'),
        ('Salesloft', 'salesloft'),
        ('Saltbox', 'saltbox'),
        ('Sanity', 'sanity'),
        ('Saronic', 'saronic'),
        ('Scholarrock', 'scholarrock'),
        ('Schonfeld', 'schonfeld'),
        ('Scopely', 'scopely'),
        ('Scout Motors', 'scoutmotors'),
        ('Secureframe', 'secureframe'),
        ('Sentilink', 'sentilink'),
        ('Serverobotics', 'serverobotics'),
        ('Shields Health Solutions', 'shieldshealthsolutions'),
        ('ShipMonk', 'shipmonk'),
        ('Sigma Computing', 'sigmacomputing'),
        ('Sila', 'sila'),
        ('Sila', 'silananotechnologies'),
        ('Simpson Gumpertz & Heger', 'simpsongumpertzheger'),
        ('SingleStore', 'singlestore'),
        ('Skydio', 'skydio'),
        ('SmartRent', 'smartrent'),
        ('Smartsheet', 'smartsheet'),
        ('Snorkel AI', 'snorkelai'),
        ('Snowflake', 'snowflake'),
        ('Socure', 'socure'),
        ('Solarlandscape', 'solarlandscape'),
        ('Solidcore', 'solidcore'),
        ('Sonarsource', 'sonarsource'),
        ('Sonic Internet + Phone', 'sonic'),
        ('Sphere Entertainment Group, LLC', 'sphereentertainment'),
        ('Spire', 'spire'),
        ('Spotify', 'spotify'),
        ('StackAdapt', 'stackadapt'),
        ('Stack AV', 'stackav'),
        ('Starburst', 'starburst'),
        ('StepStone Group', 'stepstone'),
        ('Stitch Fix', 'stitchfix'),
        ('StockX', 'stockx'),
        ('Stratolaunch', 'stratolaunch'),
        ('Strive Health', 'strivehealth'),
        ('Sunday', 'sunday'),
        ('sweetgreen', 'sweetgreen'),
        ('Sword', 'swordhealth'),
        ('Syska Hennessy Group', 'syskahennessy'),
        ('TabaPay', 'tabapay'),
        ('Taboola', 'taboola'),
        ('Take-Two Interactive Software, Inc.', 'taketwo'),
        ('Talkiatry', 'talkiatry'),
        ('Talkspace', 'talkspace'),
        ('Tanium', 'tanium'),
        ('tastytrade', 'tastytrade'),
        ('Total Deployment Solutions', 'tds'),
        ('Tebra', 'tebra'),
        ('Tecovas', 'tecovas'),
        ('Tekion', 'tekion'),
        ('Thatgamecompany', 'thatgamecompany'),
        ('The Brattle Group', 'thebrattlegroup'),
        ('The Farmer''s Dog', 'thefarmersdog'),
        ('The New York Times', 'thenewyorktimes'),
        ('The Trade Desk', 'thetradedesk'),
        ('Thrive Market', 'thrivemarket'),
        ('Thumbtack', 'thumbtack'),
        ('Titan', 'titan'),
        ('Tonal', 'tonal'),
        ('Toptal', 'toptal'),
        ('Torc Robotics', 'torcrobotics'),
        ('Triumvirate Environmental', 'triumvirateenvironmental'),
        ('Trulioo', 'trulioo'),
        ('Truveta', 'truveta'),
        ('Ttecdigital', 'ttecdigital'),
        ('Tulip Interfaces', 'tulip'),
        ('Twist Bioscience', 'twistbioscience'),
        ('Twitch', 'twitch'),
        ('Two Six Technologies', 'twosixtechnologies'),
        ('Uber Freight', 'uberfreight'),
        ('Ultima Genomics', 'ultimagenomics'),
        ('Upstart', 'upstart'),
        ('Ursa Major', 'ursamajor'),
        ('Vaco LLC', 'vaco'),
        ('Valon', 'valon'),
        ('Vannevar', 'vannevarlabs'),
        ('Varda Space Industries', 'vardaspace'),
        ('Vast', 'vast'),
        ('Vaxcyte', 'vaxcyte'),
        ('VaynerMedia LLC', 'vaynermedia'),
        ('Velo3d', 'velo3d'),
        ('Venusaero', 'venusaero'),
        ('Veracyte', 'veracyte'),
        ('Verve', 'verve'),
        ('Via', 'via'),
        ('Virtu Financial', 'virtu'),
        ('Volta', 'volta'),
        ('Vox Media Group', 'voxmedia'),
        ('VTS', 'vts'),
        ('Vultr', 'vultr'),
        ('Wasabi Technologies', 'wasabi'),
        ('Waymo', 'waymo'),
        ('Wealthfront', 'wealthfront'),
        ('Weee! Inc', 'weee'),
        ('Whoop', 'whoop'),
        ('William Blair', 'williamblair'),
        ('Wise Worksite Field Sales', 'wise'),
        ('Wonderschool', 'wonderschool'),
        ('Woodardcurran', 'woodardcurran'),
        ('Woolpert', 'woolpert'),
        ('Workato', 'workato'),
        ('WPP', 'wpp'),
        ('Wpromote', 'wpromote'),
        ('Xaira Therapeutics', 'xairatherapeutics'),
        ('Xcimer', 'xcimer'),
        ('Xometry', 'xometry'),
        ('Zeta Global', 'zetaglobal'),
        ('ZoomInfo Technologies LLC', 'zoominfo'),
        ('Zoox', 'zoox'),
        ('Zoro', 'zoro'),
        ('Zscaler', 'zscaler'),
        ('Zuora', 'zuora')
)
INSERT INTO external_companies (name, normalized_name)
SELECT name, normalized_name
FROM companies
ON CONFLICT (normalized_name) DO UPDATE SET
    name = EXCLUDED.name,
    is_active = true,
    updated_at = CURRENT_TIMESTAMP;

WITH sources(normalized_name, source_type, board_token, source_name) AS (
    VALUES
        ('absorblms', 'ASHBY', 'absorblms', 'Ashby'),
        ('airwallex', 'ASHBY', 'airwallex', 'Ashby'),
        ('amplify', 'ASHBY', 'amplify', 'Ashby'),
        ('angi', 'ASHBY', 'angi', 'Ashby'),
        ('applied', 'ASHBY', 'applied', 'Ashby'),
        ('assembledhq', 'ASHBY', 'assembledhq', 'Ashby'),
        ('astra', 'ASHBY', 'astra', 'Ashby'),
        ('benchling', 'ASHBY', 'benchling', 'Ashby'),
        ('bestow', 'ASHBY', 'bestow', 'Ashby'),
        ('brightwheel', 'ASHBY', 'brightwheel', 'Ashby'),
        ('brigit', 'ASHBY', 'brigit', 'Ashby'),
        ('clickhouse', 'ASHBY', 'clickhouse', 'Ashby'),
        ('clickup', 'ASHBY', 'clickup', 'Ashby'),
        ('commure', 'ASHBY', 'commure', 'Ashby'),
        ('curri', 'ASHBY', 'curri', 'Ashby'),
        ('dandelion', 'ASHBY', 'dandelion', 'Ashby'),
        ('delinea', 'ASHBY', 'delinea', 'Ashby'),
        ('deposco', 'ASHBY', 'deposco', 'Ashby'),
        ('docker', 'ASHBY', 'docker', 'Ashby'),
        ('eightsleep', 'ASHBY', 'eightsleep', 'Ashby'),
        ('envoy', 'ASHBY', 'envoy', 'Ashby'),
        ('formenergy', 'ASHBY', 'formenergy', 'Ashby'),
        ('handshake', 'ASHBY', 'handshake', 'Ashby'),
        ('helion', 'ASHBY', 'helion', 'Ashby'),
        ('industrious', 'ASHBY', 'industrious', 'Ashby'),
        ('inovalon', 'ASHBY', 'inovalon', 'Ashby'),
        ('insitro', 'ASHBY', 'insitro', 'Ashby'),
        ('instructure', 'ASHBY', 'instructure', 'Ashby'),
        ('junipersquare', 'ASHBY', 'junipersquare', 'Ashby'),
        ('kin', 'ASHBY', 'kin', 'Ashby'),
        ('kong', 'ASHBY', 'kong', 'Ashby'),
        ('langchain', 'ASHBY', 'langchain', 'Ashby'),
        ('latchbio', 'ASHBY', 'latchbio', 'Ashby'),
        ('meridianlink', 'ASHBY', 'meridianlink', 'Ashby'),
        ('method', 'ASHBY', 'method', 'Ashby'),
        ('nerdwallet', 'ASHBY', 'nerdwallet', 'Ashby'),
        ('notable', 'ASHBY', 'notable', 'Ashby'),
        ('nubank', 'ASHBY', 'nubank', 'Ashby'),
        ('opengov', 'ASHBY', 'opengov', 'Ashby'),
        ('paxos', 'ASHBY', 'paxos', 'Ashby'),
        ('poshmark', 'ASHBY', 'poshmark', 'Ashby'),
        ('primer', 'ASHBY', 'primer', 'Ashby'),
        ('rothys', 'ASHBY', 'rothys', 'Ashby'),
        ('runpod', 'ASHBY', 'runpod', 'Ashby'),
        ('sanity', 'ASHBY', 'sanity', 'Ashby'),
        ('saronic', 'ASHBY', 'saronic', 'Ashby'),
        ('secureframe', 'ASHBY', 'secureframe', 'Ashby'),
        ('sentilink', 'ASHBY', 'sentilink', 'Ashby'),
        ('serverobotics', 'ASHBY', 'serverobotics', 'Ashby'),
        ('skydio', 'ASHBY', 'skydio', 'Ashby'),
        ('snowflake', 'ASHBY', 'snowflake', 'Ashby'),
        ('socure', 'ASHBY', 'socure', 'Ashby'),
        ('sunday', 'ASHBY', 'sunday', 'Ashby'),
        ('talkiatry', 'ASHBY', 'talkiatry', 'Ashby'),
        ('tekion', 'ASHBY', 'tekion', 'Ashby'),
        ('thatgamecompany', 'ASHBY', 'thatgamecompany', 'Ashby'),
        ('thumbtack', 'ASHBY', 'thumbtack', 'Ashby'),
        ('titan', 'ASHBY', 'titan', 'Ashby'),
        ('tonal', 'ASHBY', 'tonal', 'Ashby'),
        ('trulioo', 'ASHBY', 'trulioo', 'Ashby'),
        ('valon', 'ASHBY', 'valon', 'Ashby'),
        ('volta', 'ASHBY', 'volta', 'Ashby'),
        ('vultr', 'ASHBY', 'vultr', 'Ashby'),
        ('whoop', 'ASHBY', 'whoop', 'Ashby'),
        ('4dmoleculartherapeutics', 'GREENHOUSE', '4dmoleculartherapeutics', 'Greenhouse'),
        ('6sense', 'GREENHOUSE', '6sense', 'Greenhouse'),
        ('abacus', 'GREENHOUSE', 'abacus', 'Greenhouse'),
        ('abnormalsecurity', 'GREENHOUSE', 'abnormalsecurity', 'Greenhouse'),
        ('accela', 'GREENHOUSE', 'accela', 'Greenhouse'),
        ('achievementfirst', 'GREENHOUSE', 'achievementfirst', 'Greenhouse'),
        ('aclu', 'GREENHOUSE', 'aclu', 'Greenhouse'),
        ('adyen', 'GREENHOUSE', 'adyen', 'Greenhouse'),
        ('aegworldwide', 'GREENHOUSE', 'aegworldwide', 'Greenhouse'),
        ('aftership', 'GREENHOUSE', 'aftership', 'Greenhouse'),
        ('agilityrobotics', 'GREENHOUSE', 'agilityrobotics', 'Greenhouse'),
        ('albedo', 'GREENHOUSE', 'albedo', 'Greenhouse'),
        ('alertmedia', 'GREENHOUSE', 'alertmedia', 'Greenhouse'),
        ('alloy', 'GREENHOUSE', 'alloy', 'Greenhouse'),
        ('alnylampharmaceuticals', 'GREENHOUSE', 'alnylampharmaceuticals', 'Greenhouse'),
        ('aloyoga', 'GREENHOUSE', 'aloyoga', 'Greenhouse'),
        ('alphasights', 'GREENHOUSE', 'alphasights', 'Greenhouse'),
        ('altoslabs', 'GREENHOUSE', 'altoslabs', 'Greenhouse'),
        ('altruist', 'GREENHOUSE', 'altruist', 'Greenhouse'),
        ('amn', 'GREENHOUSE', 'amn', 'Greenhouse'),
        ('amwins', 'GREENHOUSE', 'amwins', 'Greenhouse'),
        ('anaplan', 'GREENHOUSE', 'anaplan', 'Greenhouse'),
        ('antora', 'GREENHOUSE', 'antora', 'Greenhouse'),
        ('apexcompanies', 'GREENHOUSE', 'apexcompanies', 'Greenhouse'),
        ('applovin', 'GREENHOUSE', 'applovin', 'Greenhouse'),
        ('apptronik', 'GREENHOUSE', 'apptronik', 'Greenhouse'),
        ('aqr', 'GREENHOUSE', 'aqr', 'Greenhouse'),
        ('arcinstitute', 'GREENHOUSE', 'arcinstitute', 'Greenhouse'),
        ('asana', 'GREENHOUSE', 'asana', 'Greenhouse'),
        ('assetliving', 'GREENHOUSE', 'assetliving', 'Greenhouse'),
        ('astranis', 'GREENHOUSE', 'astranis', 'Greenhouse'),
        ('atlasair', 'GREENHOUSE', 'atlasair', 'Greenhouse'),
        ('attentive', 'GREENHOUSE', 'attentive', 'Greenhouse'),
        ('axios', 'GREENHOUSE', 'axios', 'Greenhouse'),
        ('axsometherapeutics', 'GREENHOUSE', 'axsometherapeutics', 'Greenhouse'),
        ('ayahealthcare', 'GREENHOUSE', 'ayahealthcare', 'Greenhouse'),
        ('bandwidth', 'GREENHOUSE', 'bandwidth', 'Greenhouse'),
        ('bankrate', 'GREENHOUSE', 'bankrate', 'Greenhouse'),
        ('beamtherapeutics', 'GREENHOUSE', 'beamtherapeutics', 'Greenhouse'),
        ('betterment', 'GREENHOUSE', 'betterment', 'Greenhouse'),
        ('beyondtrust', 'GREENHOUSE', 'beyondtrust', 'Greenhouse'),
        ('billcom', 'GREENHOUSE', 'billcom', 'Greenhouse'),
        ('bird', 'GREENHOUSE', 'bird', 'Greenhouse'),
        ('bitgo', 'GREENHOUSE', 'bitgo', 'Greenhouse'),
        ('blacksky', 'GREENHOUSE', 'blacksky', 'Greenhouse'),
        ('blankstreet', 'GREENHOUSE', 'blankstreet', 'Greenhouse'),
        ('blend', 'GREENHOUSE', 'blend', 'Greenhouse'),
        ('bombas', 'GREENHOUSE', 'bombas', 'Greenhouse'),
        ('bouldercare', 'GREENHOUSE', 'bouldercare', 'Greenhouse'),
        ('brainlabs', 'GREENHOUSE', 'brainlabs', 'Greenhouse'),
        ('braze', 'GREENHOUSE', 'braze', 'Greenhouse'),
        ('bridgebio', 'GREENHOUSE', 'bridgebio', 'Greenhouse'),
        ('budderfly', 'GREENHOUSE', 'budderfly', 'Greenhouse'),
        ('buildops', 'GREENHOUSE', 'buildops', 'Greenhouse'),
        ('businessolver', 'GREENHOUSE', 'businessolver', 'Greenhouse'),
        ('butterflynetwork', 'GREENHOUSE', 'butterflynetwork', 'Greenhouse'),
        ('calicolabs', 'GREENHOUSE', 'calicolabs', 'Greenhouse'),
        ('cannondesign', 'GREENHOUSE', 'cannondesign', 'Greenhouse'),
        ('capco', 'GREENHOUSE', 'capco', 'Greenhouse'),
        ('carbon', 'GREENHOUSE', 'carbon', 'Greenhouse'),
        ('carbonrobotics', 'GREENHOUSE', 'carbonrobotics', 'Greenhouse'),
        ('caregiver', 'GREENHOUSE', 'caregiver', 'Greenhouse'),
        ('cargurus', 'GREENHOUSE', 'cargurus', 'Greenhouse'),
        ('carta', 'GREENHOUSE', 'carta', 'Greenhouse'),
        ('celigo', 'GREENHOUSE', 'celigo', 'Greenhouse'),
        ('chanzuckerberginitiative', 'GREENHOUSE', 'chanzuckerberginitiative', 'Greenhouse'),
        ('chargepoint', 'GREENHOUSE', 'chargepoint', 'Greenhouse'),
        ('charlesriverassociates', 'GREENHOUSE', 'charlesriverassociates', 'Greenhouse'),
        ('charliehealth', 'GREENHOUSE', 'charliehealth', 'Greenhouse'),
        ('checkr', 'GREENHOUSE', 'checkr', 'Greenhouse'),
        ('classpass', 'GREENHOUSE', 'classpass', 'Greenhouse'),
        ('clearstreet', 'GREENHOUSE', 'clearstreet', 'Greenhouse'),
        ('cloverhealth', 'GREENHOUSE', 'cloverhealth', 'Greenhouse'),
        ('coalition', 'GREENHOUSE', 'coalition', 'Greenhouse'),
        ('codeandtheory', 'GREENHOUSE', 'codeandtheory', 'Greenhouse'),
        ('collibra', 'GREENHOUSE', 'collibra', 'Greenhouse'),
        ('colossalbiosciences', 'GREENHOUSE', 'colossalbiosciences', 'Greenhouse'),
        ('commvault', 'GREENHOUSE', 'commvault', 'Greenhouse'),
        ('conga', 'GREENHOUSE', 'conga', 'Greenhouse'),
        ('cortland', 'GREENHOUSE', 'cortland', 'Greenhouse'),
        ('crossriverbank', 'GREENHOUSE', 'crossriverbank', 'Greenhouse'),
        ('crunchyroll', 'GREENHOUSE', 'crunchyroll', 'Greenhouse'),
        ('cypresscreekrenewables', 'GREENHOUSE', 'cypresscreekrenewables', 'Greenhouse'),
        ('datacamp', 'GREENHOUSE', 'datacamp', 'Greenhouse'),
        ('dealpath', 'GREENHOUSE', 'dealpath', 'Greenhouse'),
        ('dialpad', 'GREENHOUSE', 'dialpad', 'Greenhouse'),
        ('diligentrobotics', 'GREENHOUSE', 'diligentrobotics', 'Greenhouse'),
        ('disco', 'GREENHOUSE', 'disco', 'Greenhouse'),
        ('divergent', 'GREENHOUSE', 'divergent', 'Greenhouse'),
        ('dlrgroup', 'GREENHOUSE', 'dlrgroup', 'Greenhouse'),
        ('dotmatics', 'GREENHOUSE', 'dotmatics', 'Greenhouse'),
        ('dragos', 'GREENHOUSE', 'dragos', 'Greenhouse'),
        ('dynetherapeutics', 'GREENHOUSE', 'dynetherapeutics', 'Greenhouse'),
        ('earnin', 'GREENHOUSE', 'earnin', 'Greenhouse'),
        ('edgewisetherapeutics', 'GREENHOUSE', 'edgewisetherapeutics', 'Greenhouse'),
        ('edmentum', 'GREENHOUSE', 'edmentum', 'Greenhouse'),
        ('elationhealth', 'GREENHOUSE', 'elationhealth', 'Greenhouse'),
        ('electraaero', 'GREENHOUSE', 'electraaero', 'Greenhouse'),
        ('elevationscreditunion', 'GREENHOUSE', 'elevationscreditunion', 'Greenhouse'),
        ('elite', 'GREENHOUSE', 'elite', 'Greenhouse'),
        ('epirus', 'GREENHOUSE', 'epirus', 'Greenhouse'),
        ('everlane', 'GREENHOUSE', 'everlane', 'Greenhouse'),
        ('everlaw', 'GREENHOUSE', 'everlaw', 'Greenhouse'),
        ('exiger', 'GREENHOUSE', 'exiger', 'Greenhouse'),
        ('fahertybrand', 'GREENHOUSE', 'fahertybrand', 'Greenhouse'),
        ('fastly', 'GREENHOUSE', 'fastly', 'Greenhouse'),
        ('fictiv', 'GREENHOUSE', 'fictiv', 'Greenhouse'),
        ('fieldwire', 'GREENHOUSE', 'fieldwire', 'Greenhouse'),
        ('fireblocks', 'GREENHOUSE', 'fireblocks', 'Greenhouse'),
        ('five9', 'GREENHOUSE', 'five9', 'Greenhouse'),
        ('fleetio', 'GREENHOUSE', 'fleetio', 'Greenhouse'),
        ('flix', 'GREENHOUSE', 'flix', 'Greenhouse'),
        ('forbes', 'GREENHOUSE', 'forbes', 'Greenhouse'),
        ('formic', 'GREENHOUSE', 'formic', 'Greenhouse'),
        ('freenome', 'GREENHOUSE', 'freenome', 'Greenhouse'),
        ('galileo', 'GREENHOUSE', 'galileo', 'Greenhouse'),
        ('gemini', 'GREENHOUSE', 'gemini', 'Greenhouse'),
        ('generatebiomedicines', 'GREENHOUSE', 'generatebiomedicines', 'Greenhouse'),
        ('geniussports', 'GREENHOUSE', 'geniussports', 'Greenhouse'),
        ('geotab', 'GREENHOUSE', 'geotab', 'Greenhouse'),
        ('gillig', 'GREENHOUSE', 'gillig', 'Greenhouse'),
        ('ginkgobioworks', 'GREENHOUSE', 'ginkgobioworks', 'Greenhouse'),
        ('globalizationpartners', 'GREENHOUSE', 'globalizationpartners', 'Greenhouse'),
        ('glossier', 'GREENHOUSE', 'glossier', 'Greenhouse'),
        ('gomotive', 'GREENHOUSE', 'gomotive', 'Greenhouse'),
        ('googlefiber', 'GREENHOUSE', 'googlefiber', 'Greenhouse'),
        ('guidepoint', 'GREENHOUSE', 'guidepoint', 'Greenhouse'),
        ('harbingermotors', 'GREENHOUSE', 'harbingermotors', 'Greenhouse'),
        ('harrys', 'GREENHOUSE', 'harrys', 'Greenhouse'),
        ('hasbro', 'GREENHOUSE', 'hasbro', 'Greenhouse'),
        ('hawkeye360', 'GREENHOUSE', 'hawkeye360', 'Greenhouse'),
        ('healthverity', 'GREENHOUSE', 'healthverity', 'Greenhouse'),
        ('hearst', 'GREENHOUSE', 'hearst', 'Greenhouse'),
        ('hellofresh', 'GREENHOUSE', 'hellofresh', 'Greenhouse'),
        ('hextechnologies', 'GREENHOUSE', 'hextechnologies', 'Greenhouse'),
        ('holderconstruction', 'GREENHOUSE', 'holderconstruction', 'Greenhouse'),
        ('homechef', 'GREENHOUSE', 'homechef', 'Greenhouse'),
        ('homelight', 'GREENHOUSE', 'homelight', 'Greenhouse'),
        ('hugeinc', 'GREENHOUSE', 'hugeinc', 'Greenhouse'),
        ('huntress', 'GREENHOUSE', 'huntress', 'Greenhouse'),
        ('hyliion', 'GREENHOUSE', 'hyliion', 'Greenhouse'),
        ('imc', 'GREENHOUSE', 'imc', 'Greenhouse'),
        ('intercom', 'GREENHOUSE', 'intercom', 'Greenhouse'),
        ('iovancebiotherapeutics', 'GREENHOUSE', 'iovancebiotherapeutics', 'Greenhouse'),
        ('isomorphiclabs', 'GREENHOUSE', 'isomorphiclabs', 'Greenhouse'),
        ('ixllearning', 'GREENHOUSE', 'ixllearning', 'Greenhouse'),
        ('janestreet', 'GREENHOUSE', 'janestreet', 'Greenhouse'),
        ('kailera', 'GREENHOUSE', 'kailera', 'Greenhouse'),
        ('kairospower', 'GREENHOUSE', 'kairospower', 'Greenhouse'),
        ('kbs', 'GREENHOUSE', 'kbs', 'Greenhouse'),
        ('keepersecurity', 'GREENHOUSE', 'keepersecurity', 'Greenhouse'),
        ('kiniksapharmaceuticals', 'GREENHOUSE', 'kiniksapharmaceuticals', 'Greenhouse'),
        ('knowbe4', 'GREENHOUSE', 'knowbe4', 'Greenhouse'),
        ('kodiak', 'GREENHOUSE', 'kodiak', 'Greenhouse'),
        ('komodohealth', 'GREENHOUSE', 'komodohealth', 'Greenhouse'),
        ('kymeratherapeutics', 'GREENHOUSE', 'kymeratherapeutics', 'Greenhouse'),
        ('lendingtree', 'GREENHOUSE', 'lendingtree', 'Greenhouse'),
        ('liftoff', 'GREENHOUSE', 'liftoff', 'Greenhouse'),
        ('lightmatter', 'GREENHOUSE', 'lightmatter', 'Greenhouse'),
        ('litify', 'GREENHOUSE', 'litify', 'Greenhouse'),
        ('logicgate', 'GREENHOUSE', 'logicgate', 'Greenhouse'),
        ('lpl', 'GREENHOUSE', 'lpl', 'Greenhouse'),
        ('lucidmotors', 'GREENHOUSE', 'lucidmotors', 'Greenhouse'),
        ('luminishealth', 'GREENHOUSE', 'luminishealth', 'Greenhouse'),
        ('lyft', 'GREENHOUSE', 'lyft', 'Greenhouse'),
        ('machindustries', 'GREENHOUSE', 'machindustries', 'Greenhouse'),
        ('mavenclinic', 'GREENHOUSE', 'mavenclinic', 'Greenhouse'),
        ('mcadams', 'GREENHOUSE', 'mcadams', 'Greenhouse'),
        ('melio', 'GREENHOUSE', 'melio', 'Greenhouse'),
        ('methodcommunications', 'GREENHOUSE', 'methodcommunications', 'Greenhouse'),
        ('minio', 'GREENHOUSE', 'minio', 'Greenhouse'),
        ('misfitsmarket', 'GREENHOUSE', 'misfitsmarket', 'Greenhouse'),
        ('missionlane', 'GREENHOUSE', 'missionlane', 'Greenhouse'),
        ('mixpanel', 'GREENHOUSE', 'mixpanel', 'Greenhouse'),
        ('mntn', 'GREENHOUSE', 'mntn', 'Greenhouse'),
        ('moloco', 'GREENHOUSE', 'moloco', 'Greenhouse'),
        ('monks', 'GREENHOUSE', 'monks', 'Greenhouse'),
        ('mozilla', 'GREENHOUSE', 'mozilla', 'Greenhouse'),
        ('muonspace', 'GREENHOUSE', 'muonspace', 'Greenhouse'),
        ('natera', 'GREENHOUSE', 'natera', 'Greenhouse'),
        ('naughtydog', 'GREENHOUSE', 'naughtydog', 'Greenhouse'),
        ('neo4j', 'GREENHOUSE', 'neo4j', 'Greenhouse'),
        ('netskope', 'GREENHOUSE', 'netskope', 'Greenhouse'),
        ('neuralink', 'GREENHOUSE', 'neuralink', 'Greenhouse'),
        ('newrelic', 'GREENHOUSE', 'newrelic', 'Greenhouse'),
        ('newsela', 'GREENHOUSE', 'newsela', 'Greenhouse'),
        ('nex', 'GREENHOUSE', 'nex', 'Greenhouse'),
        ('nexamp', 'GREENHOUSE', 'nexamp', 'Greenhouse'),
        ('nice', 'GREENHOUSE', 'nice', 'Greenhouse'),
        ('nintendo', 'GREENHOUSE', 'nintendo', 'Greenhouse'),
        ('nurix', 'GREENHOUSE', 'nurix', 'Greenhouse'),
        ('nuro', 'GREENHOUSE', 'nuro', 'Greenhouse'),
        ('officeally', 'GREENHOUSE', 'officeally', 'Greenhouse'),
        ('ogilvy', 'GREENHOUSE', 'ogilvy', 'Greenhouse'),
        ('oklo', 'GREENHOUSE', 'oklo', 'Greenhouse'),
        ('olema', 'GREENHOUSE', 'olema', 'Greenhouse'),
        ('olsson', 'GREENHOUSE', 'olsson', 'Greenhouse'),
        ('omadahealth', 'GREENHOUSE', 'omadahealth', 'Greenhouse'),
        ('onemedical', 'GREENHOUSE', 'onemedical', 'Greenhouse'),
        ('onrunning', 'GREENHOUSE', 'onrunning', 'Greenhouse'),
        ('opentable', 'GREENHOUSE', 'opentable', 'Greenhouse'),
        ('ophelia', 'GREENHOUSE', 'ophelia', 'Greenhouse'),
        ('oportun', 'GREENHOUSE', 'oportun', 'Greenhouse'),
        ('orchard', 'GREENHOUSE', 'orchard', 'Greenhouse'),
        ('otter', 'GREENHOUSE', 'otter', 'Greenhouse'),
        ('oura', 'GREENHOUSE', 'oura', 'Greenhouse'),
        ('pacificfusion', 'GREENHOUSE', 'pacificfusion', 'Greenhouse'),
        ('pagaya', 'GREENHOUSE', 'pagaya', 'Greenhouse'),
        ('parachutehome', 'GREENHOUSE', 'parachutehome', 'Greenhouse'),
        ('pathrobotics', 'GREENHOUSE', 'pathrobotics', 'Greenhouse'),
        ('pieinsurance', 'GREENHOUSE', 'pieinsurance', 'Greenhouse'),
        ('planetlabs', 'GREENHOUSE', 'planetlabs', 'Greenhouse'),
        ('point72', 'GREENHOUSE', 'point72', 'Greenhouse'),
        ('prove', 'GREENHOUSE', 'prove', 'Greenhouse'),
        ('psiquantum', 'GREENHOUSE', 'psiquantum', 'Greenhouse'),
        ('pubmatic', 'GREENHOUSE', 'pubmatic', 'Greenhouse'),
        ('purestorage', 'GREENHOUSE', 'purestorage', 'Greenhouse'),
        ('qt', 'GREENHOUSE', 'qt', 'Greenhouse'),
        ('quaise', 'GREENHOUSE', 'quaise', 'Greenhouse'),
        ('qualia', 'GREENHOUSE', 'qualia', 'Greenhouse'),
        ('rebuildmanufacturing', 'GREENHOUSE', 'rebuildmanufacturing', 'Greenhouse'),
        ('recursionpharmaceuticals', 'GREENHOUSE', 'recursionpharmaceuticals', 'Greenhouse'),
        ('redwoodmaterials', 'GREENHOUSE', 'redwoodmaterials', 'Greenhouse'),
        ('reformation', 'GREENHOUSE', 'reformation', 'Greenhouse'),
        ('relativity', 'GREENHOUSE', 'relativity', 'Greenhouse'),
        ('renttherunway', 'GREENHOUSE', 'renttherunway', 'Greenhouse'),
        ('revolutionmedicines', 'GREENHOUSE', 'revolutionmedicines', 'Greenhouse'),
        ('riotgames', 'GREENHOUSE', 'riotgames', 'Greenhouse'),
        ('roblox', 'GREENHOUSE', 'roblox', 'Greenhouse'),
        ('rocketlab', 'GREENHOUSE', 'rocketlab', 'Greenhouse'),
        ('rockstargames', 'GREENHOUSE', 'rockstargames', 'Greenhouse'),
        ('roku', 'GREENHOUSE', 'roku', 'Greenhouse'),
        ('roofstock', 'GREENHOUSE', 'roofstock', 'Greenhouse'),
        ('rti', 'GREENHOUSE', 'rti', 'Greenhouse'),
        ('rubrik', 'GREENHOUSE', 'rubrik', 'Greenhouse'),
        ('saatva', 'GREENHOUSE', 'saatva', 'Greenhouse'),
        ('salesloft', 'GREENHOUSE', 'salesloft', 'Greenhouse'),
        ('saltbox', 'GREENHOUSE', 'saltbox', 'Greenhouse'),
        ('schonfeld', 'GREENHOUSE', 'schonfeld', 'Greenhouse'),
        ('scopely', 'GREENHOUSE', 'scopely', 'Greenhouse'),
        ('scoutmotors', 'GREENHOUSE', 'scoutmotors', 'Greenhouse'),
        ('shieldshealthsolutions', 'GREENHOUSE', 'shieldshealthsolutions', 'Greenhouse'),
        ('shipmonk', 'GREENHOUSE', 'shipmonk', 'Greenhouse'),
        ('sigmacomputing', 'GREENHOUSE', 'sigmacomputing', 'Greenhouse'),
        ('silananotechnologies', 'GREENHOUSE', 'silananotechnologies', 'Greenhouse'),
        ('simpsongumpertzheger', 'GREENHOUSE', 'simpsongumpertzheger', 'Greenhouse'),
        ('singlestore', 'GREENHOUSE', 'singlestore', 'Greenhouse'),
        ('smartrent', 'GREENHOUSE', 'smartrent', 'Greenhouse'),
        ('smartsheet', 'GREENHOUSE', 'smartsheet', 'Greenhouse'),
        ('snorkelai', 'GREENHOUSE', 'snorkelai', 'Greenhouse'),
        ('sonic', 'GREENHOUSE', 'sonic', 'Greenhouse'),
        ('sphereentertainment', 'GREENHOUSE', 'sphereentertainment', 'Greenhouse'),
        ('spire', 'GREENHOUSE', 'spire', 'Greenhouse'),
        ('stackadapt', 'GREENHOUSE', 'stackadapt', 'Greenhouse'),
        ('stackav', 'GREENHOUSE', 'stackav', 'Greenhouse'),
        ('starburst', 'GREENHOUSE', 'starburst', 'Greenhouse'),
        ('stepstone', 'GREENHOUSE', 'stepstone', 'Greenhouse'),
        ('stitchfix', 'GREENHOUSE', 'stitchfix', 'Greenhouse'),
        ('stockx', 'GREENHOUSE', 'stockx', 'Greenhouse'),
        ('stratolaunch', 'GREENHOUSE', 'stratolaunch', 'Greenhouse'),
        ('strivehealth', 'GREENHOUSE', 'strivehealth', 'Greenhouse'),
        ('sweetgreen', 'GREENHOUSE', 'sweetgreen', 'Greenhouse'),
        ('swordhealth', 'GREENHOUSE', 'swordhealth', 'Greenhouse'),
        ('syskahennessy', 'GREENHOUSE', 'syskahennessy', 'Greenhouse'),
        ('tabapay', 'GREENHOUSE', 'tabapay', 'Greenhouse'),
        ('taboola', 'GREENHOUSE', 'taboola', 'Greenhouse'),
        ('taketwo', 'GREENHOUSE', 'taketwo', 'Greenhouse'),
        ('talkspace', 'GREENHOUSE', 'talkspace', 'Greenhouse'),
        ('tanium', 'GREENHOUSE', 'tanium', 'Greenhouse'),
        ('tastytrade', 'GREENHOUSE', 'tastytrade', 'Greenhouse'),
        ('tds', 'GREENHOUSE', 'tds', 'Greenhouse'),
        ('tebra', 'GREENHOUSE', 'tebra', 'Greenhouse'),
        ('tecovas', 'GREENHOUSE', 'tecovas', 'Greenhouse'),
        ('thebrattlegroup', 'GREENHOUSE', 'thebrattlegroup', 'Greenhouse'),
        ('thefarmersdog', 'GREENHOUSE', 'thefarmersdog', 'Greenhouse'),
        ('thenewyorktimes', 'GREENHOUSE', 'thenewyorktimes', 'Greenhouse'),
        ('thetradedesk', 'GREENHOUSE', 'thetradedesk', 'Greenhouse'),
        ('thrivemarket', 'GREENHOUSE', 'thrivemarket', 'Greenhouse'),
        ('torcrobotics', 'GREENHOUSE', 'torcrobotics', 'Greenhouse'),
        ('triumvirateenvironmental', 'GREENHOUSE', 'triumvirateenvironmental', 'Greenhouse'),
        ('truveta', 'GREENHOUSE', 'truveta', 'Greenhouse'),
        ('tulip', 'GREENHOUSE', 'tulip', 'Greenhouse'),
        ('twistbioscience', 'GREENHOUSE', 'twistbioscience', 'Greenhouse'),
        ('twitch', 'GREENHOUSE', 'twitch', 'Greenhouse'),
        ('twosixtechnologies', 'GREENHOUSE', 'twosixtechnologies', 'Greenhouse'),
        ('uberfreight', 'GREENHOUSE', 'uberfreight', 'Greenhouse'),
        ('ultimagenomics', 'GREENHOUSE', 'ultimagenomics', 'Greenhouse'),
        ('upstart', 'GREENHOUSE', 'upstart', 'Greenhouse'),
        ('ursamajor', 'GREENHOUSE', 'ursamajor', 'Greenhouse'),
        ('vaco', 'GREENHOUSE', 'vaco', 'Greenhouse'),
        ('vannevarlabs', 'GREENHOUSE', 'vannevarlabs', 'Greenhouse'),
        ('vardaspace', 'GREENHOUSE', 'vardaspace', 'Greenhouse'),
        ('vast', 'GREENHOUSE', 'vast', 'Greenhouse'),
        ('vaxcyte', 'GREENHOUSE', 'vaxcyte', 'Greenhouse'),
        ('vaynermedia', 'GREENHOUSE', 'vaynermedia', 'Greenhouse'),
        ('veracyte', 'GREENHOUSE', 'veracyte', 'Greenhouse'),
        ('verve', 'GREENHOUSE', 'verve', 'Greenhouse'),
        ('via', 'GREENHOUSE', 'via', 'Greenhouse'),
        ('virtu', 'GREENHOUSE', 'virtu', 'Greenhouse'),
        ('voxmedia', 'GREENHOUSE', 'voxmedia', 'Greenhouse'),
        ('vts', 'GREENHOUSE', 'vts', 'Greenhouse'),
        ('wasabi', 'GREENHOUSE', 'wasabi', 'Greenhouse'),
        ('waymo', 'GREENHOUSE', 'waymo', 'Greenhouse'),
        ('weee', 'GREENHOUSE', 'weee', 'Greenhouse'),
        ('williamblair', 'GREENHOUSE', 'williamblair', 'Greenhouse'),
        ('wise', 'GREENHOUSE', 'wise', 'Greenhouse'),
        ('wonderschool', 'GREENHOUSE', 'wonderschool', 'Greenhouse'),
        ('woolpert', 'GREENHOUSE', 'woolpert', 'Greenhouse'),
        ('workato', 'GREENHOUSE', 'workato', 'Greenhouse'),
        ('wpp', 'GREENHOUSE', 'wpp', 'Greenhouse'),
        ('xairatherapeutics', 'GREENHOUSE', 'xairatherapeutics', 'Greenhouse'),
        ('xometry', 'GREENHOUSE', 'xometry', 'Greenhouse'),
        ('zetaglobal', 'GREENHOUSE', 'zetaglobal', 'Greenhouse'),
        ('zoominfo', 'GREENHOUSE', 'zoominfo', 'Greenhouse'),
        ('zoro', 'GREENHOUSE', 'zoro', 'Greenhouse'),
        ('zscaler', 'GREENHOUSE', 'zscaler', 'Greenhouse'),
        ('zuora', 'GREENHOUSE', 'zuora', 'Greenhouse'),
        ('aeva', 'LEVER', 'aeva', 'Lever'),
        ('aledade', 'LEVER', 'aledade', 'Lever'),
        ('allegiantair', 'LEVER', 'allegiantair', 'Lever'),
        ('anchorage', 'LEVER', 'anchorage', 'Lever'),
        ('angellist', 'LEVER', 'angellist', 'Lever'),
        ('arcadia', 'LEVER', 'arcadia', 'Lever'),
        ('arrivelogistics', 'LEVER', 'arrivelogistics', 'Lever'),
        ('bannerbank', 'LEVER', 'bannerbank', 'Lever'),
        ('bluebottlecoffee', 'LEVER', 'bluebottlecoffee', 'Lever'),
        ('bounteous', 'LEVER', 'bounteous', 'Lever'),
        ('brooksrunning', 'LEVER', 'brooksrunning', 'Lever'),
        ('dadavidson', 'LEVER', 'dadavidson', 'Lever'),
        ('entrata', 'LEVER', 'entrata', 'Lever'),
        ('everlywell', 'LEVER', 'everlywell', 'Lever'),
        ('filevine', 'LEVER', 'filevine', 'Lever'),
        ('freedomprep', 'LEVER', 'freedomprep', 'Lever'),
        ('gopuff', 'LEVER', 'gopuff', 'Lever'),
        ('hermeus', 'LEVER', 'hermeus', 'Lever'),
        ('insomniacookies', 'LEVER', 'insomniacookies', 'Lever'),
        ('jamcity', 'LEVER', 'jamcity', 'Lever'),
        ('jetsupport', 'LEVER', 'jetsupport', 'Lever'),
        ('kippsocal', 'LEVER', 'kippsocal', 'Lever'),
        ('lessen', 'LEVER', 'lessen', 'Lever'),
        ('lifestance', 'LEVER', 'lifestance', 'Lever'),
        ('merlinlabs', 'LEVER', 'merlinlabs', 'Lever'),
        ('pattern', 'LEVER', 'pattern', 'Lever'),
        ('picklerobot', 'LEVER', 'picklerobot', 'Lever'),
        ('pigment', 'LEVER', 'pigment', 'Lever'),
        ('pointclickcare', 'LEVER', 'pointclickcare', 'Lever'),
        ('prosper', 'LEVER', 'prosper', 'Lever'),
        ('protolabs', 'LEVER', 'protolabs', 'Lever'),
        ('redwoodcu', 'LEVER', 'redwoodcu', 'Lever'),
        ('rocketship', 'LEVER', 'rocketship', 'Lever'),
        ('scholarrock', 'LEVER', 'scholarrock', 'Lever'),
        ('secureframe', 'LEVER', 'secureframe', 'Lever'),
        ('sila', 'LEVER', 'sila', 'Lever'),
        ('solarlandscape', 'LEVER', 'solarlandscape', 'Lever'),
        ('solidcore', 'LEVER', 'solidcore', 'Lever'),
        ('sonarsource', 'LEVER', 'sonarsource', 'Lever'),
        ('spotify', 'LEVER', 'spotify', 'Lever'),
        ('toptal', 'LEVER', 'toptal', 'Lever'),
        ('ttecdigital', 'LEVER', 'ttecdigital', 'Lever'),
        ('velo3d', 'LEVER', 'velo3d', 'Lever'),
        ('venusaero', 'LEVER', 'venusaero', 'Lever'),
        ('wealthfront', 'LEVER', 'wealthfront', 'Lever'),
        ('woodardcurran', 'LEVER', 'woodardcurran', 'Lever'),
        ('wpromote', 'LEVER', 'wpromote', 'Lever'),
        ('xcimer', 'LEVER', 'xcimer', 'Lever'),
        ('zoox', 'LEVER', 'zoox', 'Lever')
)
INSERT INTO external_job_sources (company_id, source_type, board_token, source_name)
SELECT c.id, s.source_type, s.board_token, s.source_name
FROM sources s
JOIN external_companies c ON c.normalized_name = s.normalized_name
ON CONFLICT (source_type, board_token) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    is_active = true,
    last_error = NULL,
    updated_at = CURRENT_TIMESTAMP;
